<?php
require __DIR__.'/app.php';
if(isset($_GET['logout'])){ session_destroy(); header('Location: ?page=login'); exit; }
$page=$_GET['page']??'dashboard';
if($page==='login'){
 if(logged_in()){header('Location: ?page=dashboard');exit;}
 $error=null;
 if($_SERVER['REQUEST_METHOD']==='POST'){
  check_csrf(); $email=trim($_POST['email']??''); $password=$_POST['password']??'';
  $s=$pdo->prepare('SELECT id,name,email,password_hash FROM users WHERE email=? LIMIT 1');$s->execute([$email]);$u=$s->fetch();
  if($u && password_verify($password,$u['password_hash'])){$_SESSION['user_id']=$u['id'];$_SESSION['user_name']=$u['name'];header('Location: ?page=dashboard');exit;}
  $error='Invalid email or password.';
 }
 ?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Login · WebStripe AI CRM</title><link rel="stylesheet" href="assets/app.css"></head><body class="login"><form method="post" class="login-card"><div class="brand">WebStripe <span>AI CRM</span></div><h1>Welcome back</h1><?php if($error):?><div class="error"><?=e($error)?></div><?php endif; ?><input type="hidden" name="csrf" value="<?=e(csrf())?>"><label>Email<input type="email" name="email" required autofocus></label><label>Password<input type="password" name="password" required></label><button class="button wide">Sign in</button></form></body></html><?php exit;
}
require_login();
if($page==='dashboard'){
 layout_start('Dashboard');
 $total=(int)$pdo->query('SELECT COUNT(*) FROM leads')->fetchColumn();$open=(int)$pdo->query("SELECT COUNT(*) FROM leads WHERE status NOT IN ('won','lost')")->fetchColumn();$won=(int)$pdo->query("SELECT COUNT(*) FROM leads WHERE status='won'")->fetchColumn();$value=(float)$pdo->query("SELECT COALESCE(SUM(value),0) FROM leads WHERE status='won'")->fetchColumn();
 $recent=$pdo->query('SELECT id,name,company,status,value,ai_score,created_at FROM leads ORDER BY created_at DESC LIMIT 8')->fetchAll();
 ?><section class="stats"><div><small>Total Leads</small><strong><?=$total?></strong></div><div><small>Open Leads</small><strong><?=$open?></strong></div><div><small>Won Leads</small><strong><?=$won?></strong></div><div><small>Won Value</small><strong>₹<?=number_format($value,0)?></strong></div></section><section class="card"><div class="card-head"><h2>Recent Leads</h2><a href="?page=leads">View all</a></div><table><tr><th>Name</th><th>Company</th><th>Status</th><th>AI Score</th><th>Value</th></tr><?php foreach($recent as $l):?><tr><td><a href="?page=lead&id=<?=$l['id']?>"><?=e($l['name'])?></a></td><td><?=e($l['company'])?></td><td><span class="badge <?=e($l['status'])?>"><?=e(ucfirst($l['status']))?></span></td><td><?=is_null($l['ai_score'])?'—':e($l['ai_score']).'/100'?></td><td>₹<?=number_format((float)$l['value'],0)?></td></tr><?php endforeach;?></table></section><?php layout_end();exit;
}
if($page==='leads'){
 if($_SERVER['REQUEST_METHOD']==='POST'){check_csrf();$name=trim($_POST['name']??'');if($name===''){flash('Lead name is required.');header('Location: ?page=leads&action=new');exit;}$s=$pdo->prepare('INSERT INTO leads(name,email,phone,company,source,status,value,follow_up_at,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)');$s->execute([$name,trim($_POST['email']??''),trim($_POST['phone']??''),trim($_POST['company']??''),trim($_POST['source']??'website'),$_POST['status']??'new',(float)($_POST['value']??0),($_POST['follow_up_at']??'')?:null,trim($_POST['notes']??''),$_SESSION['user_id']]);flash('Lead created.');header('Location: ?page=leads');exit;}
 layout_start('Leads');$q=trim($_GET['q']??'');if($q){$s=$pdo->prepare('SELECT * FROM leads WHERE name LIKE ? OR email LIKE ? OR company LIKE ? ORDER BY created_at DESC');$x="%$q%";$s->execute([$x,$x,$x]);$leads=$s->fetchAll();}else{$leads=$pdo->query('SELECT * FROM leads ORDER BY created_at DESC')->fetchAll();}
 if(($_GET['action']??'')==='new'){ ?><section class="card form-card"><h2>Create Lead</h2><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><div class="grid"><label>Name*<input name="name" required></label><label>Company<input name="company"></label><label>Email<input type="email" name="email"></label><label>Phone<input name="phone"></label><label>Source<select name="source"><option>website</option><option>referral</option><option>linkedin</option><option>facebook</option><option>google</option><option>outbound</option><option>other</option></select></label><label>Value (₹)<input type="number" step="0.01" name="value" value="0"></label><label>Follow-up<input type="datetime-local" name="follow_up_at"></label><label>Status<select name="status"><option>new</option><option>contacted</option><option>qualified</option><option>proposal</option><option>won</option><option>lost</option></select></label></div><label>Notes<textarea name="notes"></textarea></label><button class="button">Create Lead</button></form></section><?php }
 ?><section class="card"><div class="card-head"><h2>All Leads</h2><form class="search"><input name="q" placeholder="Search name, company, email" value="<?=e($q)?>"><input type="hidden" name="page" value="leads"><button>Search</button></form></div><table><tr><th>Name</th><th>Company</th><th>Contact</th><th>Status</th><th>AI</th><th>Follow-up</th></tr><?php foreach($leads as $l):?><tr><td><a href="?page=lead&id=<?=$l['id']?>"><?=e($l['name'])?></a></td><td><?=e($l['company']?:'—')?></td><td><?=e($l['email']?:$l['phone']?:'—')?></td><td><span class="badge <?=e($l['status'])?>"><?=e(ucfirst($l['status']))?></span></td><td><?=is_null($l['ai_score'])?'—':e($l['ai_score']).'/100'?></td><td><?=e($l['follow_up_at']?:'—')?></td></tr><?php endforeach;?></table></section><?php layout_end();exit;
}
if($page==='pipeline'){
 layout_start('Pipeline');$st=['new','contacted','qualified','proposal','won','lost'];?><div class="pipeline"><?php foreach($st as $status){$s=$pdo->prepare('SELECT id,name,company,value,ai_score FROM leads WHERE status=? ORDER BY updated_at DESC');$s->execute([$status]);?><div class="column"><h3><?=e(ucfirst($status))?></h3><?php foreach($s as $l):?><a class="lead-card" href="?page=lead&id=<?=$l['id']?>"><strong><?=e($l['name'])?></strong><span><?=e($l['company']?:'No company')?></span><small>₹<?=number_format((float)$l['value'],0)?> · AI <?=is_null($l['ai_score'])?'—':e($l['ai_score'])?></small></a><?php endforeach;?></div><?php }?></div><?php layout_end();exit;
}
if($page==='lead'){
 $id=(int)($_GET['id']??0);$s=$pdo->prepare('SELECT * FROM leads WHERE id=?');$s->execute([$id]);$lead=$s->fetch();if(!$lead){http_response_code(404);exit('Lead not found');}
 if($_SERVER['REQUEST_METHOD']==='POST'){check_csrf();$status=$_POST['status']??$lead['status'];$s=$pdo->prepare('UPDATE leads SET status=?,notes=?,follow_up_at=?,updated_at=NOW() WHERE id=?');$s->execute([$status,trim($_POST['notes']??''),($_POST['follow_up_at']??'')?:null,$id]);flash('Lead updated.');header('Location: ?page=lead&id='.$id);exit;}
 layout_start($lead['name']);$a=$pdo->prepare('SELECT * FROM activities WHERE lead_id=? ORDER BY created_at DESC');$a->execute([$id]);$activities=$a->fetchAll();?><section class="two-col"><div class="card"><div class="profile"><div><h2><?=e($lead['name'])?></h2><p><?=e($lead['company']?:'')?></p></div><button class="button" onclick="analyzeLead(<?=$id?>)">✨ AI Analyze</button></div><div class="details"><p><b>Email</b><br><?=e($lead['email']?:'—')?></p><p><b>Phone</b><br><?=e($lead['phone']?:'—')?></p><p><b>Source</b><br><?=e($lead['source'])?></p><p><b>Value</b><br>₹<?=number_format((float)$lead['value'],0)?></p><p><b>AI Score</b><br><span id="ai-score"><?=is_null($lead['ai_score'])?'Not analyzed':e($lead['ai_score']).'/100'?></span></p></div><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><label>Status<select name="status"><?php foreach(['new','contacted','qualified','proposal','won','lost'] as $x):?><option <?=($x===$lead['status']?'selected':'')?>><?=e($x)?></option><?php endforeach;?></select></label><label>Follow-up<input type="datetime-local" name="follow_up_at" value="<?=e($lead['follow_up_at']?date('Y-m-d\TH:i',strtotime($lead['follow_up_at'])):'')?></label><label>Notes<textarea name="notes"><?=e($lead['notes'])?></textarea></label><button class="button">Save Changes</button></form></div><div class="card"><h2>Activity Timeline</h2><?php foreach($activities as $x):?><div class="activity"><b><?=e(ucfirst($x['type']))?></b><span><?=e($x['description'])?></span><small><?=e($x['created_at'])?></small></div><?php endforeach;?></div></section><script>async function analyzeLead(id){const r=await fetch('api/ai.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'id='+encodeURIComponent(id)+'&csrf='+encodeURIComponent('<?=e(csrf())?>')});const d=await r.json();if(d.ok){document.getElementById('ai-score').textContent=d.score+'/100';alert(d.summary+'\n\nNext: '+d.next_action);}else alert(d.error||'AI analysis failed');}</script><?php layout_end();exit;
}
header('Location: ?page=dashboard');
