<?php
require_once __DIR__ . '/../app/bootstrap.php';
require_auth();
$pdo = db();

$pipeline = $pdo->query("SELECT status, COUNT(*) AS total, COALESCE(SUM(value),0) AS value FROM leads GROUP BY status")->fetchAll();
$bySource = $pdo->query("SELECT COALESCE(NULLIF(source,''),'unknown') AS source, COUNT(*) AS total, COALESCE(SUM(value),0) AS value FROM leads GROUP BY COALESCE(NULLIF(source,''),'unknown') ORDER BY total DESC, value DESC LIMIT 10")->fetchAll();
$topLeads = $pdo->query("SELECT id,name,company,status,value,ai_score,ai_priority FROM leads ORDER BY value DESC, ai_score DESC LIMIT 10")->fetchAll();
$conversion = (int)$pdo->query("SELECT COUNT(*) FROM leads WHERE status='won'")->fetchColumn();
$total = (int)$pdo->query("SELECT COUNT(*) FROM leads")->fetchColumn();
$openValue = (float)$pdo->query("SELECT COALESCE(SUM(value),0) FROM leads WHERE status IN ('new','contacted','qualified','proposal')")->fetchColumn();
$wonValue = (float)$pdo->query("SELECT COALESCE(SUM(value),0) FROM leads WHERE status='won'")->fetchColumn();
$overdue = (int)$pdo->query("SELECT COUNT(*) FROM tasks WHERE status='pending' AND due_at IS NOT NULL AND due_at < NOW()")->fetchColumn();
$statusLabels=['new'=>'New','contacted'=>'Contacted','qualified'=>'Qualified','proposal'=>'Proposal','won'=>'Won','lost'=>'Lost'];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Analytics | AI CRM</title><link rel="stylesheet" href="assets/app.css"></head><body>
<header class="topbar"><div class="brand">AI CRM</div><nav><a href="index.php">Dashboard</a><a href="leads.php">Leads</a><a href="pipeline.php">Pipeline</a><a href="tasks.php">Tasks</a><a href="analytics.php">Analytics</a><a href="logout.php">Logout</a></nav></header>
<main class="container"><div class="page-head"><div><p class="eyebrow">INSIGHTS</p><h1>Sales analytics</h1><p class="muted">Understand pipeline health, conversion and lead sources.</p></div></div>
<section class="stats"><article><span>Total leads</span><strong><?=$total?></strong></article><article><span>Win rate</span><strong><?=$total?round(($conversion/$total)*100):0?>%</strong></article><article><span>Open pipeline</span><strong>₹<?=number_format($openValue,0)?></strong></article><article><span>Won revenue</span><strong>₹<?=number_format($wonValue,0)?></strong></article></section>
<div class="form-grid"><section class="panel"><div class="panel-head"><h2>Pipeline by stage</h2></div><?php foreach($pipeline as $row):?><div class="metric-row"><div><strong><?=e($statusLabels[$row['status']]??ucfirst($row['status']))?></strong><span class="muted small"> <?=$row['total']?> leads</span></div><strong>₹<?=number_format((float)$row['value'],0)?></strong></div><?php endforeach;?></section><section class="panel"><div class="panel-head"><h2>Lead sources</h2></div><?php if(!$bySource):?><div class="empty">No source data yet.</div><?php endif;?><?php foreach($bySource as $row):?><div class="metric-row"><div><strong><?=e(ucfirst($row['source']))?></strong><span class="muted small"> <?=$row['total']?> leads</span></div><strong>₹<?=number_format((float)$row['value'],0)?></strong></div><?php endforeach;?></section></div>
<section class="panel" style="margin-top:18px"><div class="panel-head"><h2>Top opportunities</h2><span class="muted small">Highest value leads</span></div><div class="table-wrap"><table><thead><tr><th>Lead</th><th>Company</th><th>Stage</th><th>Value</th><th>AI score</th><th>Priority</th></tr></thead><tbody><?php if(!$topLeads):?><tr><td colspan="6" class="empty">No leads yet.</td></tr><?php endif;?><?php foreach($topLeads as $lead):?><tr><td><a href="lead-view.php?id=<?=$lead['id']?>"><strong><?=e($lead['name'])?></strong></a></td><td><?=e($lead['company'])?:'—'?></td><td><span class="pill"><?=e($statusLabels[$lead['status']]??ucfirst($lead['status']))?></span></td><td>₹<?=number_format((float)$lead['value'],0)?></td><td><?=$lead['ai_score']!==null?(int)$lead['ai_score'].'/100':'—'?></td><td><?=e($lead['ai_priority']??'—')?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel" style="margin-top:18px"><div class="panel-head"><h2>Action center</h2></div><div class="quick-grid"><a class="quick-card" href="tasks.php?filter=overdue"><strong><?=$overdue?></strong><span>Overdue tasks</span></a><a class="quick-card" href="leads.php?status=qualified"><strong>Qualified</strong><span>Review hot opportunities</span></a><a class="quick-card" href="lead-campaigns.php"><strong>Campaigns</strong><span>Generate and manage campaigns</span></a><a class="quick-card" href="web-prospecting.php"><strong>Prospecting</strong><span>Find new business opportunities</span></a></div></section>
</main></body></html>
