<?php
require_once __DIR__ . '/../app/bootstrap.php';
require_auth();
$pdo = db();
$user = current_user();
$stats = [
    'total' => (int)$pdo->query("SELECT COUNT(*) FROM leads")->fetchColumn(),
    'open' => (int)$pdo->query("SELECT COUNT(*) FROM leads WHERE status IN ('new','contacted','qualified','proposal')")->fetchColumn(),
    'qualified' => (int)$pdo->query("SELECT COUNT(*) FROM leads WHERE status='qualified'")->fetchColumn(),
    'won' => (int)$pdo->query("SELECT COUNT(*) FROM leads WHERE status='won'")->fetchColumn(),
    'value' => (float)$pdo->query("SELECT COALESCE(SUM(value),0) FROM leads WHERE status IN ('new','contacted','qualified','proposal')")->fetchColumn(),
    'won_value' => (float)$pdo->query("SELECT COALESCE(SUM(value),0) FROM leads WHERE status='won'")->fetchColumn(),
    'overdue' => (int)$pdo->query("SELECT COUNT(*) FROM tasks WHERE status='pending' AND due_at IS NOT NULL AND due_at < NOW()")->fetchColumn(),
    'today_tasks' => (int)$pdo->query("SELECT COUNT(*) FROM tasks WHERE status='pending' AND due_at IS NOT NULL AND DATE(due_at)=CURDATE()")->fetchColumn(),
];
$recent = $pdo->query("SELECT * FROM leads ORDER BY created_at DESC LIMIT 8")->fetchAll();
$followups = $pdo->query("SELECT id,name,company,status,value,follow_up_at FROM leads WHERE follow_up_at IS NOT NULL AND follow_up_at >= NOW() ORDER BY follow_up_at ASC LIMIT 6")->fetchAll();
$tasks = $pdo->query("SELECT t.id,t.title,t.due_at,t.priority,l.id AS lead_id,l.name AS lead_name FROM tasks t LEFT JOIN leads l ON l.id=t.lead_id WHERE t.status='pending' ORDER BY t.due_at IS NULL,t.due_at ASC LIMIT 6")->fetchAll();
$stages = ['new'=>'New','contacted'=>'Contacted','qualified'=>'Qualified','proposal'=>'Proposal','won'=>'Won','lost'=>'Lost'];
$stageData = $pdo->query("SELECT status,COUNT(*) total,COALESCE(SUM(value),0) value FROM leads GROUP BY status")->fetchAll();
$stageMap=[];foreach($stageData as $row)$stageMap[$row['status']]=$row;
$sources=$pdo->query("SELECT COALESCE(NULLIF(source,''),'unknown') source,COUNT(*) total,COALESCE(SUM(value),0) value FROM leads GROUP BY COALESCE(NULLIF(source,''),'unknown') ORDER BY total DESC LIMIT 5")->fetchAll();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dashboard | AI CRM</title><link rel="stylesheet" href="assets/app.css"></head><body>
<header class="topbar"><div class="brand">WebStripe <span>AI CRM</span></div><nav><a class="active" href="index.php">Dashboard</a><a href="leads.php">Leads</a><a href="pipeline.php">Pipeline</a><a href="tasks.php">Tasks</a><a href="analytics.php">Analytics</a><a href="lead-campaigns.php">Campaigns</a><a href="web-prospecting.php">Prospecting</a><a href="ai-assistant.php">AI</a><a href="logout.php">Logout</a></nav></header>
<main class="container wide"><div class="page-head"><div><p class="eyebrow">WEBSTRIPE TECHNOLOGIES · SALES COMMAND CENTER</p><h1>Good to see you, <?=e($user['name']??'User')?>.</h1><p class="muted">Turn new prospects into qualified opportunities and keep every follow-up on track.</p></div><div class="head-actions"><a class="btn" href="web-prospecting.php">Find prospects</a><a class="btn primary" href="lead-create.php">+ Add lead</a></div></div>
<section class="stats"><article><span>Total leads</span><strong><?=$stats['total']?></strong><small class="muted">All prospects in CRM</small></article><article><span>Qualified leads</span><strong><?=$stats['qualified']?></strong><small class="muted">Ready for sales action</small></article><article><span>Open pipeline</span><strong>₹<?=number_format($stats['value'],0)?></strong><small class="muted"><?=$stats['open']?> active opportunities</small></article><article><span>Won revenue</span><strong>₹<?=number_format($stats['won_value'],0)?></strong><small class="muted"><?=$stats['won']?> won deals</small></article></section>
<div class="command-grid"><section class="panel"><div class="panel-head"><div><h2>Pipeline health</h2><span class="muted small">Lead distribution by stage</span></div><a href="pipeline.php">Open pipeline →</a></div><div class="funnel"><?php foreach($stages as $key=>$label):$row=$stageMap[$key]??['total'=>0,'value'=>0];$width=$stats['total']?max(8,round(((int)$row['total']/$stats['total'])*100)):8;?><div class="funnel-row"><span><?=$label?></span><div class="funnel-bar"><i style="width:<?=$width?>%"></i></div><b><?=$row['total']?></b><em>₹<?=number_format((float)$row['value'],0)?></em></div><?php endforeach;?></div></section><section class="panel"><div class="panel-head"><div><h2>Today's workload</h2><span class="muted small">Stay ahead of follow-ups</span></div><a href="tasks.php">All tasks →</a></div><div class="workload"><div><strong><?=$stats['today_tasks']?></strong><span>Due today</span></div><div><strong><?=$stats['overdue']?></strong><span>Overdue</span></div><div><strong><?=$stats['qualified']?></strong><span>Qualified leads</span></div></div><?php if($tasks):?><div class="mini-tasks"><?php foreach($tasks as $task):?><a href="tasks.php"><span><?=e($task['title'])?></span><small><?= $task['due_at']?e(date('d M, h:i A',strtotime($task['due_at']))):'No due date'?></small></a><?php endforeach;?></div><?php endif;?></section></div>
<div class="form-grid dashboard-lower"><section class="panel"><div class="panel-head"><h2>Lead sources</h2><a href="analytics.php">Full report →</a></div><?php if(!$sources):?><div class="empty">No lead-source data yet.</div><?php endif;?><?php foreach($sources as $source):?><div class="metric-row"><div><strong><?=e(ucfirst($source['source']))?></strong><div class="muted small"><?=$source['total']?> leads</div></div><strong>₹<?=number_format((float)$source['value'],0)?></strong></div><?php endforeach;?></section><section class="panel"><div class="panel-head"><h2>Upcoming follow-ups</h2><a href="leads.php">View leads →</a></div><?php if(!$followups):?><div class="empty">No upcoming follow-ups scheduled.</div><?php endif;?><?php foreach($followups as $lead):?><div class="metric-row"><div><a href="lead-view.php?id=<?=$lead['id']?>"><strong><?=e($lead['name'])?></strong></a><div class="muted small"><?=e($lead['company'])?:'No company'?> · <?=e($stages[$lead['status']]??ucfirst($lead['status']))?></div></div><span><?=e(date('d M, h:i A',strtotime($lead['follow_up_at'])))?></span></div><?php endforeach;?></section></div>
<section class="panel" style="margin-top:18px"><div class="panel-head"><div><h2>Recent leads</h2><span class="muted small">Latest prospects entering the CRM</span></div><a href="leads.php">View all →</a></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Company</th><th>Source</th><th>Stage</th><th>Value</th><th>AI score</th><th>Created</th></tr></thead><tbody><?php if(!$recent):?><tr><td colspan="7" class="empty">No leads yet. Add your first lead or connect a capture source.</td></tr><?php endif;?><?php foreach($recent as $lead):?><tr><td><a href="lead-view.php?id=<?=$lead['id']?>"><strong><?=e($lead['name'])?></strong></a><br><span class="muted small"><?=e($lead['email'])?></span></td><td><?=e($lead['company'])?:'—'?></td><td><?=e($lead['source'])?:'—'?></td><td><span class="pill"><?=e($stages[$lead['status']]??ucfirst($lead['status']))?></span></td><td>₹<?=number_format((float)$lead['value'],0)?></td><td><?= $lead['ai_score']!==null?(int)$lead['ai_score'].'/100':'Pending'?></td><td><?=e(date('d M Y',strtotime($lead['created_at'])))?></td></tr><?php endforeach;?></tbody></table></div></section></main></body></html>
