<?php
require_once __DIR__ . '/../app/bootstrap.php';
require_auth();
$pdo = db();
$stats = [
    'total' => (int)$pdo->query("SELECT COUNT(*) FROM leads")->fetchColumn(),
    'open' => (int)$pdo->query("SELECT COUNT(*) FROM leads WHERE status IN ('new','contacted','qualified','proposal')")->fetchColumn(),
    'won' => (int)$pdo->query("SELECT COUNT(*) FROM leads WHERE status='won'")->fetchColumn(),
    'value' => (float)$pdo->query("SELECT COALESCE(SUM(value),0) FROM leads WHERE status IN ('new','contacted','qualified','proposal')")->fetchColumn(),
    'won_value' => (float)$pdo->query("SELECT COALESCE(SUM(value),0) FROM leads WHERE status='won'")->fetchColumn(),
    'overdue' => (int)$pdo->query("SELECT COUNT(*) FROM tasks WHERE status='pending' AND due_at IS NOT NULL AND due_at < NOW()")->fetchColumn(),
];
$recent = $pdo->query("SELECT * FROM leads ORDER BY created_at DESC LIMIT 8")->fetchAll();
$followups = $pdo->query("SELECT id,name,company,status,value,follow_up_at FROM leads WHERE follow_up_at IS NOT NULL AND follow_up_at >= NOW() ORDER BY follow_up_at ASC LIMIT 6")->fetchAll();
$user = current_user();
$statusLabels = ['new'=>'New','contacted'=>'Contacted','qualified'=>'Qualified','proposal'=>'Proposal','won'=>'Won','lost'=>'Lost'];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dashboard | AI CRM</title><link rel="stylesheet" href="assets/app.css"></head><body>
<header class="topbar"><div class="brand">AI CRM</div><nav><a href="index.php">Dashboard</a><a href="leads.php">Leads</a><a href="pipeline.php">Pipeline</a><a href="tasks.php">Tasks</a><a href="analytics.php">Analytics</a><a href="logout.php">Logout</a></nav></header>
<main class="container"><div class="page-head"><div><p class="eyebrow">SALES WORKSPACE</p><h1>Dashboard</h1><p class="muted">Welcome, <?=e($user['name']??'User')?>. Here is your sales snapshot.</p></div><div class="head-actions"><a class="btn" href="tasks.php">+ New task</a><a class="btn primary" href="lead-create.php">+ Add lead</a></div></div>
<section class="stats"><article><span>Total leads</span><strong><?=$stats['total']?></strong><small class="muted">All prospects</small></article><article><span>Open leads</span><strong><?=$stats['open']?></strong><small class="muted">Active opportunities</small></article><article><span>Won revenue</span><strong>₹<?=number_format($stats['won_value'],0)?></strong><small class="muted">Closed won</small></article><article><span>Open pipeline</span><strong>₹<?=number_format($stats['value'],0)?></strong><small class="muted"><?=$stats['overdue']?> overdue tasks</small></article></section>
<div class="quick-grid"><a class="quick-card" href="leads.php"><strong>Leads</strong><span>Search, filter and manage prospects</span></a><a class="quick-card" href="pipeline.php"><strong>Pipeline</strong><span>Move deals through every stage</span></a><a class="quick-card" href="tasks.php"><strong>Tasks</strong><span>Plan calls, meetings and follow-ups</span></a><a class="quick-card" href="ai-assistant.php"><strong>AI Assistant</strong><span>Analyze leads and get next actions</span></a></div>
<div class="form-grid"><section class="panel"><div class="panel-head"><h2>Upcoming follow-ups</h2><a href="leads.php">View leads</a></div><?php if(!$followups):?><div class="empty">No upcoming follow-ups scheduled.</div><?php endif;?><?php foreach($followups as $lead):?><div class="metric-row"><div><a href="lead-view.php?id=<?=$lead['id']?>"><strong><?=e($lead['name'])?></strong></a><div class="muted small"><?=e($lead['company'])?:'No company'?> · <?=e($statusLabels[$lead['status']]??ucfirst($lead['status']))?></div></div><span><?=e(date('d M, h:i A',strtotime($lead['follow_up_at'])))?></span></div><?php endforeach;?></section><section class="panel"><div class="panel-head"><h2>Sales actions</h2><a href="analytics.php">Analytics</a></div><div class="action-list"><a href="tasks.php?filter=overdue"><span>Overdue tasks</span><b><?=$stats['overdue']?></b></a><a href="leads.php?status=qualified"><span>Qualified leads</span><b>→</b></a><a href="lead-campaigns.php"><span>Lead campaigns</span><b>→</b></a><a href="web-prospecting.php"><span>Web prospecting</span><b>→</b></a></div></section></div>
<section class="panel" style="margin-top:18px"><div class="panel-head"><h2>Recent leads</h2><a href="leads.php">View all</a></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Company</th><th>Status</th><th>Value</th><th>AI score</th><th>Created</th></tr></thead><tbody><?php if(!$recent):?><tr><td colspan="6" class="empty">No leads yet. Add your first lead.</td></tr><?php endif;?><?php foreach($recent as $lead):?><tr><td><a href="lead-view.php?id=<?=$lead['id']?>"><?=e($lead['name'])?></a></td><td><?=e($lead['company'])?:'—'?></td><td><span class="pill"><?=e($statusLabels[$lead['status']] ?? ucfirst($lead['status']))?></span></td><td>₹<?=number_format((float)$lead['value'],0)?></td><td><?= $lead['ai_score']!==null?(int)$lead['ai_score'].'/100':'Pending'?></td><td><?=e(date('d M Y',strtotime($lead['created_at'])))?></td></tr><?php endforeach;?></tbody></table></div></section></main></body></html>
